rootProject.name = "Thinkrchive"
include(
    ":androidApp",
    ":desktopApp",
    ":common:all-features",
    ":common:data",
    ":common:features:about",
    ":common:features:settings",
    ":common:features:list",
    ":common:features:details",
    ":common:features:donate",
    ":common:persistence:database",
    ":common:persistence:settings",
    ":common:model",
    ":common:mvvm-core",
    ":common:network",
    ":common:integration",
    ":common:billing",
    ":web-kt-js"
)